//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Leaderboards.Internal.Http;



namespace Unity.Services.Leaderboards.Internal.Models
{
    /// <summary>
    /// LeaderboardVersions model
    /// </summary>
    [Preserve]
    [DataContract(Name = "LeaderboardVersions")]
    internal class LeaderboardVersions
    {
        /// <summary>
        /// Creates an instance of LeaderboardVersions.
        /// </summary>
        /// <param name="leaderboardId">leaderboardId param</param>
        /// <param name="results">results param</param>
        /// <param name="nextReset">nextReset param</param>
        [Preserve]
        public LeaderboardVersions(string leaderboardId = default, List<LeaderboardVersion> results = default, DateTime nextReset = default)
        {
            LeaderboardId = leaderboardId;
            Results = results;
            NextReset = nextReset;
        }

        /// <summary>
        /// Parameter leaderboardId of LeaderboardVersions
        /// </summary>
        [Preserve]
        [DataMember(Name = "leaderboardId", EmitDefaultValue = false)]
        public string LeaderboardId{ get; }

        /// <summary>
        /// Parameter results of LeaderboardVersions
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<LeaderboardVersion> Results{ get; }

        /// <summary>
        /// Parameter nextReset of LeaderboardVersions
        /// </summary>
        [Preserve]
        [DataMember(Name = "nextReset", EmitDefaultValue = false)]
        public DateTime NextReset{ get; }

        /// <summary>
        /// Formats a LeaderboardVersions into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (LeaderboardId != null)
            {
                serializedModel += "leaderboardId," + LeaderboardId + ",";
            }
            if (Results != null)
            {
                serializedModel += "results," + Results.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a LeaderboardVersions as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (LeaderboardId != null)
            {
                var leaderboardIdStringValue = LeaderboardId.ToString();
                dictionary.Add("leaderboardId", leaderboardIdStringValue);
            }

            return dictionary;
        }
    }
}
